#!/bin/bash

# get testscript path
script_under_test=$(realpath change-commit-author.sh)

# store current dir
current_dir=$(pwd)

wrong_author="John"
wrong_email="john@example.com"
committer_date="2020-01-01T00:00:00"

right_author="Alice"
right_email="alice@example.com"

function add_commit() {
  # set committer date to 1st of January 2020
  git commit -m "$1" --allow-empty --date "${committer_date}"
}

function git_log() {
  git log --pretty=format:" %aN %x09 %aE %cn %ce %x09 %ad %x09 %s %ci" > $1
}

# set up
temp_dir=$(mktemp -d)
echo "created temp dir: ${temp_dir}"

# # initialize git
cd ${temp_dir}
git init

# # add several commits by John
git config user.name "${wrong_author}"
git config user.email "${wrong_email}"

# disable gpg signing for testing
git config user.signingkey "" 
git config commit.gpgsign false 
git config core.pager ''

add_commit "commit A"
add_commit "commit B"
add_commit "commit C"

git_log "commits_by_john.txt"

# run script
echo "------------------------ Running script ------------------------"
echo "Running script: ${script_under_test} ${wrong_email} ${right_author} ${right_email}"
sh ${script_under_test} ${wrong_email} ${right_author} ${right_email}
echo "------------------------ Script finished ------------------------"

# # commit authour is now Alice
git_log "commits_by_alice.txt"

# check the expectations
echo ""
echo "------------------------ Checking differences ------------------------"
diff commits_by_john.txt commits_by_alice.txt
echo ""
echo "------------------------ Differences checked ------------------------"

failed_tests_messages=()

# assert that wrong author is not present
if grep -q "${wrong_author}" commits_by_alice.txt; then
  failed_tests_messages+=("Wrong author is present. Expected ${wrong_author} to be replaced by ${right_author}")
fi

# assert that wrong email is not present
if grep -q "${wrong_email}" commits_by_alice.txt; then
  failed_tests_messages+=("Wrong email is present. Expected ${wrong_email} to be replaced by ${right_email}")
fi

# assert that current date is not present
current_date=$(date +"%Y-%m-%d")
if grep -q "${current_date}" commits_by_alice.txt; then
  failed_tests_messages+=("Current date is present. Expected ${committer_date} to stay unchanged in the commit history")
fi

echo "------------------------ Cleaning up ------------------------"
rm -rf "${temp_dir}" && echo "removed temp dir: ${temp_dir}"
cd "${current_dir}"
echo "------------------------ Cleaned up ------------------------"
echo ""

exit_code=0
if [ ${#failed_tests_messages[@]} -eq 0 ]; then
  echo "------------------------ All tests passed ------------------------"
else
  echo "------------------------ Tests failed ------------------------"
  for message in "${failed_tests_messages[@]}"; do
    echo "* ${message}"
  done
  exit_code=1
fi

exit ${exit_code}

